window.LectureTCIData = {
  items: [
    {
      id: "q1",
      factor: "E",
      reverseFactor: "I",
      text: "새로운 사람들과 함께 있을 때 에너지가 생기는 편이다.",
      order: 1,
    },
    {
      id: "q2",
      factor: "I",
      reverseFactor: "E",
      text: "혼자 생각을 정리한 뒤 말하는 편이 편하다.",
      order: 2,
    },
    {
      id: "q3",
      factor: "N",
      reverseFactor: "S",
      text: "구체적인 사실보다 가능성과 의미를 먼저 떠올린다.",
      order: 3,
    },
    {
      id: "q4",
      factor: "S",
      reverseFactor: "N",
      text: "설명은 실제 사례와 절차가 있을 때 더 잘 이해된다.",
      order: 4,
    },
    {
      id: "q5",
      factor: "T",
      reverseFactor: "F",
      text: "결정할 때 감정보다 기준과 원칙을 우선한다.",
      order: 5,
    },
    {
      id: "q6",
      factor: "F",
      reverseFactor: "T",
      text: "판단할 때 사람에게 미칠 영향을 먼저 생각한다.",
      order: 6,
    },
    {
      id: "q7",
      factor: "J",
      reverseFactor: "P",
      text: "일정과 계획이 분명할수록 마음이 편하다.",
      order: 7,
    },
    {
      id: "q8",
      factor: "P",
      reverseFactor: "J",
      text: "상황에 맞춰 유연하게 바꾸는 편이 자연스럽다.",
      order: 8,
    },
  ],
  participants: [
    { id: "A102", status: "completed", progress: 100 },
    { id: "B317", status: "in_progress", progress: 63 },
    { id: "C044", status: "in_progress", progress: 38 },
    { id: "D825", status: "not_started", progress: 0 },
    { id: "E219", status: "completed", progress: 100 },
    { id: "F610", status: "in_progress", progress: 75 },
    { id: "G502", status: "not_started", progress: 0 },
    { id: "H118", status: "completed", progress: 100 },
    { id: "J704", status: "in_progress", progress: 50 },
    { id: "K933", status: "in_progress", progress: 25 },
    { id: "L081", status: "completed", progress: 100 },
    { id: "M347", status: "not_started", progress: 0 },
    { id: "N629", status: "in_progress", progress: 88 },
    { id: "P416", status: "completed", progress: 100 },
    { id: "Q205", status: "in_progress", progress: 13 },
    { id: "R772", status: "in_progress", progress: 42 },
    { id: "S390", status: "completed", progress: 100 },
    { id: "T558", status: "not_started", progress: 0 },
    { id: "U641", status: "in_progress", progress: 67 },
    { id: "V094", status: "completed", progress: 100 },
  ],
  resultCategories: [
    {
      id: "A",
      title: "방어성 척도",
      summary: "검사 응답의 솔직성 및 방어적 응답 경향을 나타내는 척도 영역입니다.",
      measures: [
        {
          id: "defe",
          name: "방어성",
          score: 52,
          level: "보통",
          tone: "yellow",
          description: "결과를 의식해 자신을 조금 긍정적으로 보이려는 경향이 있을 수 있으나, 전체 결과 해석에는 큰 문제가 없어 보입니다.",
        },
      ],
    },
    {
      id: "B",
      title: "직무환경 척도",
      summary: "소속 기관과 업무 환경에서 경험하는 조직 분위기와 직무 부담을 나타내는 척도 영역입니다.",
      measures: [
        {
          id: "clim",
          name: "조직풍토",
          score: 40,
          level: "보통",
          tone: "yellow",
          description: "교사 간 소통과 기관장의 지원이 대체로 유지되지만, 상황에 따라 도움을 충분히 받지 못한다고 느낄 수 있습니다.",
        },
        {
          id: "auto",
          name: "직무자율성",
          score: 43,
          level: "보통",
          tone: "yellow",
          description: "업무상 주요 결정을 스스로 내리는 편이나, 때로는 허락이나 확인이 필요하다고 느낄 수 있습니다.",
        },
        {
          id: "stre",
          name: "직무스트레스",
          score: 68,
          level: "높음",
          tone: "red",
          description: "업무 요구, 관계, 운영 방식 등에서 부담을 크게 경험할 가능성이 있어 정서적 피로를 함께 확인할 필요가 있습니다.",
        },
        {
          id: "turn",
          name: "이직의도",
          score: 63,
          level: "보통",
          tone: "yellow",
          description: "현재 업무와 개인 생활의 균형이 흔들릴 때 퇴직이나 이동을 고민하는 마음이 생길 수 있습니다.",
        },
        {
          id: "burn",
          name: "직무소진",
          score: 58,
          level: "보통",
          tone: "yellow",
          description: "업무로 인한 심리적, 신체적 피로가 누적되는 때가 있어 휴식과 업무 조정이 도움이 될 수 있습니다.",
        },
      ],
    },
    {
      id: "C",
      title: "성격",
      summary: "개인의 성격적 특성과 대인관계 경향을 나타내는 척도 영역입니다.",
      measures: [
        {
          id: "cons",
          name: "성실성",
          score: 74,
          level: "높음",
          tone: "green",
          description: "책임감과 계획성이 강하게 나타나며 맡은 일을 끝까지 해내려는 태도가 두드러집니다.",
        },
        {
          id: "agre",
          name: "친화성",
          score: 69,
          level: "높음",
          tone: "green",
          description: "타인의 입장을 고려하고 협력하려는 경향이 높아 관계 중심의 업무에서 강점으로 작용할 수 있습니다.",
        },
        {
          id: "opti",
          name: "낙관성",
          score: 55,
          level: "보통",
          tone: "yellow",
          description: "상황을 긍정적으로 보려는 힘이 있으나, 스트레스가 높을 때에는 기대 수준이 낮아질 수 있습니다.",
        },
        {
          id: "para",
          name: "편집성",
          score: 46,
          level: "보통",
          tone: "yellow",
          description: "대인관계에서 조심스럽게 확인하려는 경향이 있으나 일반적인 범위에 있습니다.",
        },
        {
          id: "avoi",
          name: "회피성",
          score: 61,
          level: "보통",
          tone: "yellow",
          description: "부담스러운 상황에서는 직접 맞서기보다 거리를 두고 싶어질 수 있습니다.",
        },
        {
          id: "aggr",
          name: "공격성",
          score: 49,
          level: "보통",
          tone: "yellow",
          description: "불편한 감정을 직접 표현하거나 강하게 주장하는 경향은 일반적인 범위에 있는 것으로 보입니다.",
        },
      ],
    },
    {
      id: "D",
      title: "심리적 웰빙",
      summary: "심리적 안녕감과 정서적 어려움 및 신체화 경향을 나타내는 척도 영역입니다.",
      measures: [
        {
          id: "stab",
          name: "심리적 안녕감",
          score: 47,
          level: "보통",
          tone: "yellow",
          description: "전반적인 심리 안정감은 보통 수준이나, 업무 부담이 커질 때 회복 시간이 필요할 수 있습니다.",
        },
        {
          id: "anxi",
          name: "불안과 우울",
          score: 66,
          level: "높음",
          tone: "red",
          description: "걱정이나 우울감이 비교적 높게 나타날 수 있어 최근 스트레스 요인을 구체적으로 살피는 것이 좋습니다.",
        },
        {
          id: "soma",
          name: "신체화",
          score: 59,
          level: "보통",
          tone: "yellow",
          description: "심리적 긴장이 피로, 두통, 소화 불편 등 신체 반응으로 나타나는 때가 있을 수 있습니다.",
        },
      ],
    },
    {
      id: "E",
      title: "조직화",
      summary: "주의집중과 실행기능 등 일상 및 업무 수행의 조직화 능력을 나타내는 척도 영역입니다.",
      measures: [
        {
          id: "adhd",
          name: "주의집중 문제",
          score: 57,
          level: "보통",
          tone: "yellow",
          description: "업무가 많거나 방해 자극이 많은 상황에서 집중 유지가 흔들릴 수 있습니다.",
        },
        {
          id: "exec",
          name: "실행기능",
          score: 44,
          level: "보통",
          tone: "yellow",
          description: "계획을 세우고 순서대로 처리하는 능력은 보통 수준이며, 업무량이 많을 때 우선순위 정리가 중요합니다.",
        },
      ],
    },
    {
      id: "F",
      title: "스트레스 대응전략",
      summary: "문제 상황과 스트레스에 대한 인지적 유연성 및 대처 능력을 나타내는 척도 영역입니다.",
      measures: [
        {
          id: "flex",
          name: "인지적 유연성",
          score: 71,
          level: "높음",
          tone: "green",
          description: "상황 변화에 맞추어 관점을 전환하고 대안을 찾는 능력이 비교적 강점으로 보입니다.",
        },
        {
          id: "mana",
          name: "대처능력",
          score: 63,
          level: "보통",
          tone: "yellow",
          description: "문제가 생겼을 때 해결하려는 힘이 있으나, 스트레스가 누적되면 도움 요청과 휴식 전략이 필요할 수 있습니다.",
        },
      ],
    },
  ],
};
